jqassistant:
  # The list of jQAssistant plugins to load and activate.
  scan:
    properties:
      jqassistant.plugin.antlr.grammars:
        - grammar: 'Logging.g4'
          grammarRoot: 'log'
          fileExtension: '.logging'
        - grammar: 'DOT.g4'
          grammarRoot: 'graph'
          fileExtension: '.dot'